apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blockguardian-backend-rolebinding
  labels:
    app: blockguardian-backend
    component: backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: blockguardian-backend-role
subjects:
  - kind: ServiceAccount
    name: blockguardian-backend-sa
    namespace: default
